LENGTH_HINT = "還是猜不出來嗎？單字的長度是 {answer}。"
FIRST_CHARACTER_HINT = "給你一個提示.. 第一個字是 {answer[0]}。"
FAILED_MESSAGE = "很可惜.. 答案是 {answer[0]}。"
EXIT_MESSAGE = "再見~~"
TRY_AGAIN_MESSAGE = "再想想看~"
CORRECT_MESSAGE = "答對了！還剩下 {count} 題！"
END_MESSAGE = "結束！！"
